apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  ports:
  - protocol: TCP
    port: 8030
  selector:
    app: stockmanager
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stockmanager
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
        - image: 10.128.0.6:8081/microsvc-dev/djstockmanager:10
          imagePullPolicy: Always
          name: stockmanager
          ports:
            - containerPort: 8030
